# Generated by Django 3.1.4 on 2020-12-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('market', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50, null=True)),
                ('industry', models.CharField(max_length=200, null=True)),
                ('listing_date', models.CharField(max_length=10, null=True)),
                ('settle_month', models.CharField(max_length=2, null=True)),
                ('representative', models.CharField(max_length=100, null=True)),
                ('homepage', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
